**Homework 15**

In this assignment we'll start working with PyTorch:

In [1]:
import torch
from torch.nn import Linear, ReLU, Sequential

Let's use PyTorch to recreate the Neural Network from Homework 13:

In [2]:
# network=Sequential(
#     Linear(2,3),
#     ReLU(),
#     Linear(3,1)
# )

You should be able to use it the exact same way, except that we apply PyTorch models to PyTorch tensors, rather than Numpy arrays:

In [ ]:
# X=torch.randn(15,2) #generate a random feature matrix with 2 features and 15 observations as a torch tensor
# network(X) #Predictions of our network

tensor([[-0.0813],
        [-0.1567],
        [-0.1090],
        [-0.1515],
        [-0.1346],
        [-0.1296],
        [-0.1397],
        [-0.1505],
        [-0.1515],
        [-0.1048],
        [-0.1467],
        [-0.1050],
        [-0.0586],
        [-0.1497],
        [-0.1607]], grad_fn=<AddmmBackward0>)

You can see the weights and biases of your network as follows. Note that the first layer has a weight matrix of shape (3,2) and a bias vector of size 3, and the second layer has a weight matrix of shape(1,3) and a single bias.

In [ ]:
# for param in network.parameters():
#     print(param,param.shape)

Parameter containing:
tensor([[-0.1948,  0.1002],
        [-0.5629, -0.5028],
        [ 0.2965,  0.0814]], requires_grad=True) torch.Size([3, 2])
Parameter containing:
tensor([-0.3241, -0.0396,  0.6139], requires_grad=True) torch.Size([3])
Parameter containing:
tensor([[0.4967, 0.1034, 0.1546]], requires_grad=True) torch.Size([1, 3])
Parameter containing:
tensor([-0.2588], requires_grad=True) torch.Size([1])


We now use gradient descent to train our network. Let's create a target vector:

In [ ]:
# target=torch.randn(15,1)

Our training loop now follows the pattern from Homework 14:

In [ ]:
# for i in range(10000): #Do 10000 gradient descent steps
#   network.zero_grad() #Zero out the derivative with respect to each network parameter

#   prediction=network(X) #Compute the network prediction

#   MSEloss=torch.nn.MSELoss()(prediction,mpg) #Compute MSE loss
#   #MSEloss=((prediction-target)**2).mean() #This is the same!!

#   MSEloss.backward() #Compute gradient

#   for param in network.parameters():
#     param.data-=0.01*param.grad  #Take a gradient descent step with learning rate of 0.01

#   if i%1000==0:
#     print(f"Step: {i}/10000, Loss: {MSEloss.item()}") #Periodic reporting to track progress

Step: 0/10000, Loss: 0.5272141098976135
Step: 1000/10000, Loss: 0.33072933554649353
Step: 2000/10000, Loss: 0.29391607642173767
Step: 3000/10000, Loss: 0.2762899398803711
Step: 4000/10000, Loss: 0.26108816266059875
Step: 5000/10000, Loss: 0.22926096618175507
Step: 6000/10000, Loss: 0.21057048439979553
Step: 7000/10000, Loss: 0.19926948845386505
Step: 8000/10000, Loss: 0.19221338629722595
Step: 9000/10000, Loss: 0.18711385130882263


Let's now use this on real data. We'll use the same three colunns from the `cars` dataset that we usd in Homework 5, and again use the `mpg` column for our target:

In [ ]:
# import pandas as pd
# cars=pd.read_csv('https://vincentarelbundock.github.io/Rdatasets/csv/causaldata/auto.csv')

# DWG=torch.tensor([cars.displacement,cars.weight,cars.gear_ratio],dtype=torch.float32).T
# mpg=torch.tensor(cars.mpg,dtype=torch.float32)

Define a neural network appropriate for predicting `mpg` from `DWG`. Your network should have two hidden layers with 8 neurons and 4 neurons, and ReLU layers before and after all hidden layers.

In [ ]:
# network=Sequential(
#     Linear(3,8),
#     ReLU(),
#     Linear(8,4),
#     ReLU(),
#     Linear(4,1)
# )

Write a training loop to train your network to predict `mpg` from `DWG`. Do 10000 gradient descent steps with a learning rate of 0.001, and report your MSE every 10000 steps.

In [ ]:
# for i in range(10000): #Do 10000 gradient descent steps
#   network.zero_grad() #Zero out the derivative with respect to each network parameter
#   prediction=network(DWG) #Compute the network prediction
#   #MSEloss=((prediction-mpg)**2).mean() #Compute MSE loss function
#   MSEloss=torch.nn.MSELoss()(prediction,mpg)
#   MSEloss.backward() #Compute gradient
#   for param in network.parameters():
#     param.data-=0.001*param.grad  #Take a gradient descent step with learning rate of 0.0001
#   if i%1000==0:
#     print(f"Step: {i}/10000, Loss: {MSEloss.item()}") #Periodic reporting to track progress

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/loss.py:610: UserWarning: Using a target size (torch.Size([74])) that is different to the input size (torch.Size([74, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Step: 0/10000, Loss: 13162.1240234375
Step: 1000/10000, Loss: 41.39728927612305
Step: 2000/10000, Loss: 33.17255783081055
Step: 3000/10000, Loss: 33.02251052856445
Step: 4000/10000, Loss: 33.019775390625
Step: 5000/10000, Loss: 33.01972961425781
Step: 6000/10000, Loss: 33.019718170166016
Step: 7000/10000, Loss: 33.019718170166016
Step: 8000/10000, Loss: 33.019718170166016
Step: 9000/10000, Loss: 33.019718170166016


Compute the final MSE for your trained model:

In [ ]:
# final_mse=torch.nn.MSELoss()(network(DWG),mpg).item()
# final_mse

33.019718170166016

In [ ]:
final_mse=33.019718170166016

For classification problems, here are the only changes:
1. If you are predicting $n$ classes, the final layer should have $n$ neurons.
2. For training, use Categorical Cross Entropy loss (torch.nn.CrossEntropyLoss) instead of MSE. (No need to one-hot encode target variable)
3. If you want to generate predictions of your model (to guage accuracy, for example), use: `torch.argmax(network(X), dim=1)`
4. If you want to see the probability that your model predicts each class, use: `torch.softmax(network(X), dim=1)`.

With these changes in mind, we'll revisit the iris dataset:

In [ ]:
# from sklearn.datasets import load_iris
# iris=load_iris()

# X=torch.tensor(iris.data, dtype=torch.float32)
# y=torch.tensor(iris.target, dtype=torch.long)

Create a neural network appropriate for predicting `y` from `X`, with one hidden layer that has 10 neurons, and ReLU layers before and after that:

In [ ]:
# iris_net=Sequential(
#     Linear(4,10),
#     ReLU(),
#     Linear(10,10),
#     ReLU(),
#     Linear(10,3)
# )

Train your neural network for 10000 steps, with a learning rate of 0.01:

In [ ]:
# for i in range(10000): #Do 10000 gradient descent steps
#   iris_net.zero_grad() #Zero out the derivative with respect to each network parameter
#   pred=iris_net(X) #Compute the network prediction
#   CEloss=torch.nn.CrossEntropyLoss()(pred,y) #Compute Cross Entropy loss function
#   CEloss.backward() #Compute gradient
#   for param in iris_net.parameters():
#     param.data-=0.01*param.grad  #Take a gradient descent step with learning rate of 0.01
#   if i%1000==0:
#     print(f"Step: {i}/10000, Loss: {CEloss.item()}") #Periodic reporting to track progress

Step: 0/10000, Loss: 1.2585302591323853
Step: 1000/10000, Loss: 0.1855735331773758
Step: 2000/10000, Loss: 0.08063088357448578
Step: 3000/10000, Loss: 0.06697969883680344
Step: 4000/10000, Loss: 0.06175161898136139
Step: 5000/10000, Loss: 0.05880573391914368
Step: 6000/10000, Loss: 0.05675854906439781
Step: 7000/10000, Loss: 0.05515560135245323
Step: 8000/10000, Loss: 0.05381729081273079
Step: 9000/10000, Loss: 0.05266256257891655


What is the probability that your model assigns to flower 133 being in class 1? class 2?

In [ ]:
# class1_prob=torch.softmax(iris_net(X),dim=1)[133,1].item()
# class2_prob=torch.softmax(iris_net(X),dim=1)[133,2].item()
# class1_prob,class2_prob

(0.6089670062065125, 0.3910176753997803)

In [ ]:
class1_prob=0.6089670062065125
class2_prob=0.39103299379345703

Create a vector of predictions for your model:

In [ ]:
# predictions=torch.argmax(iris_net(X),dim=1)
# predictions

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

Compute the accuracy of your model:

In [ ]:
# accuracy=(torch.argmax(iris_net(X),dim=1)==y).float().mean().item()
# accuracy

0.9800000190734863

In [ ]:
accuracy=0.9800000190734863